SISTEMA TIENDA/WEB/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WEB.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

SISTEMA TIENDA/WEB/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MODELO;

namespace WEB.Controllers
{
    public class ProductosController : Controller
    {
        SISTEMA_TIENDAEntities st = new SISTEMA_TIENDAEntities();
        
        public ActionResult NuevoProducto() //Accion GET de NuevoProducto
        {
            ViewBag.Medida = new SelectList(st.T_MEDIDA.ToList(), "Id", "Descripcion");
            return View();
        }

        [HttpPost]
        public ActionResult NuevoProducto(T_NUEVO_PRODUCTO nuevo) //Accion 
        {
            try
            {
                st.SP_NUEVO_PRODUCTO(nuevo.Codigo, nuevo.Descripcion, nuevo.IdMedida, nuevo.Volumen);
                ViewBag.Mensaje = "ok";
            }
            catch (Exception)
            {
                ViewBag.Mensaje = "no";
            }
            ViewBag.Medida = new SelectList(st.T_MEDIDA.ToList(), "Id", "Descripcion");
            return View("NuevoProducto");
        }
    }
}

SISTEMA TIENDA/WEB/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

SISTEMA TIENDA/WEB/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SISTEMA TIENDA/WEB/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

SISTEMA TIENDA/WEB/Views/Productos/NuevoProducto.cshtml
@model MODELO.T_NUEVO_PRODUCTO

@{
    ViewBag.Title = "Nuevo Producto";
    var mensaje = ViewBag.Mensaje;
}




<div class="text-center">
    <h2><strong>NUEVO PRODUCTO</strong></h2>
</div>
<br />
@if (ViewBag.Mensaje == null)
{
    <input type="hidden" id="txtOculto" value="" />
}
else
{
    <input type="hidden" id="txtOculto" value="@mensaje" />
}

<div class="row">
    <div class="col-3"></div>
    <div class="col-6" style="border:solid 0.8px; padding-top:50px;padding-bottom:50px; border-radius:15px;border-color:#D2D3D3;">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-group row">
                @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-4 d-flex justify-content-end font-weight-bold" })
                <div class="col-md-8 d-flex justify-content-start">
                    @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control", @placeholder = "CODIGO" } })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-4 d-flex justify-content-end font-weight-bold" })
                <div class="col-md-8 d-flex justify-content-start">
                    @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control", @placeholder = "NOMBRE" } })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.IdMedida, htmlAttributes: new { @class = "control-label col-md-4 d-flex justify-content-end font-weight-bold" })
                <div class="col-md-8 d-flex justify-content-start">
                    @Html.DropDownListFor(model => model.IdMedida, ViewBag.Medida as IEnumerable<SelectListItem>, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Volumen, htmlAttributes: new { @class = "control-label col-md-4 d-flex justify-content-end font-weight-bold" })
                <div class="col-md-8 d-flex justify-content-start">
                    @Html.EditorFor(model => model.Volumen, new { htmlAttributes = new { @class = "form-control", @placeholder = "VOLUMEN" } })
                </div>
            </div>

            <div class="form-group row">
                <div class="col-md-4">
                    <input type="hidden" class="col-md-4" />
                </div>
                <div class="col-md-8 d-flex justify-content-start">
                    <input type="submit" value="AGREGAR" id="btnAgregar" class="btn btn-primary btn-block" />
                </div>
            </div>


        }

    </div>
    <div class="col-3"></div>
</div>


<script src="~/Scripts/Alertas.js"></script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SISTEMA TIENDA/WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/Content/stylos.css" />
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/toastr")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-expand navbar-light fixed-top" style="background-color: #119CBB;">

        <div class="container">
            <a class="navbar-brand text-white font-weight-bold" href="#">TIENDA</a>
            <button class="navbar-toggler text-white" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                <ul class="navbar-nav ">
                    <li class="nav-item active mr-2">
                        <a class="nav-link text-white font-weight-bold" href="#">Inicio <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active mr-2">
                        <a class="nav-link text-white font-weight-bold" href="#">Link</a>
                    </li>
                    <li class="nav-item dropdown active mr-2">
                        <a class="nav-link dropdown-toggle text-white font-weight-bold" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Productos
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href='@Url.Action("NuevoProducto", "Productos")'>Nuevo Producto</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </li>
                    <li class="nav-item active mr-2">
                        <a class="nav-link text-white font-weight-bold" href="#">Disabled</a>
                    </li>
                </ul>
            </div>

        </div>
    </div>
    <div class="container body-content">
        <br />
        @RenderBody()
        <br /><br /><br />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/toastr")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>